In [1]:
import pandas as pd
import numpy as np

#시각화
import matplotlib.pyplot as plt
import seaborn as sns
plt.rc('axes', unicode_minus=False)
%matplotlib inline

In [2]:
import joblib

import pandas as pd
import numpy as np


from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [3]:
with open('../data/my_val.pkl', 'rb') as f:
    data = joblib.load(f)
locals().update(data)
del data
np.random.seed(1234)

In [8]:
x.shape

(7466, 151)

In [62]:
from sklearn.decomposition import PCA, KernelPCA

In [10]:
pca = PCA()
pca.fit(x)

PCA()

In [12]:
cumsum = np.cumsum(pca.explained_variance_ratio_)
cumsum

array([0.99960456, 0.99996423, 0.99998121, 0.99999062, 0.99999494,
       0.9999975 , 0.99999843, 0.99999898, 0.99999922, 0.99999939,
       0.99999951, 0.99999961, 0.99999968, 0.99999973, 0.99999976,
       0.99999979, 0.99999981, 0.99999983, 0.99999985, 0.99999986,
       0.99999988, 0.99999989, 0.99999989, 0.9999999 , 0.9999999 ,
       0.99999991, 0.99999991, 0.99999992, 0.99999992, 0.99999993,
       0.99999993, 0.99999993, 0.99999994, 0.99999994, 0.99999994,
       0.99999994, 0.99999995, 0.99999995, 0.99999995, 0.99999995,
       0.99999996, 0.99999996, 0.99999996, 0.99999996, 0.99999996,
       0.99999996, 0.99999997, 0.99999997, 0.99999997, 0.99999997,
       0.99999997, 0.99999997, 0.99999997, 0.99999997, 0.99999998,
       0.99999998, 0.99999998, 0.99999998, 0.99999998, 0.99999998,
       0.99999998, 0.99999998, 0.99999998, 0.99999998, 0.99999998,
       0.99999998, 0.99999998, 0.99999998, 0.99999999, 0.99999999,
       0.99999999, 0.99999999, 0.99999999, 0.99999999, 0.99999

In [13]:
d = np.argmax(cumsum >= 0.95) + 1

In [70]:
# pca = PCA(n_components=100)
# x_reduced = pca.fit_transform(x)

rbf_pca = KernelPCA(n_components=100, kernel='rbf', gamma=0.01)
x_reduced = rbf_pca.fit_transform(x)

In [71]:
x_reduced

array([[-0.00085582, -0.00103312, -0.00056571, ..., -0.00021124,
        -0.00015856, -0.00013764],
       [-0.00085706, -0.00103475, -0.00056732, ..., -0.00030863,
        -0.0002328 , -0.00020227],
       [-0.00085582, -0.00103313, -0.00056572, ..., -0.00021157,
        -0.00015881, -0.00013786],
       ...,
       [-0.00085581, -0.00103311, -0.0005657 , ..., -0.00021093,
        -0.00015832, -0.00013743],
       [-0.00085581, -0.00103311, -0.0005657 , ..., -0.00021093,
        -0.00015832, -0.00013743],
       [-0.00085592, -0.00103326, -0.00056585, ..., -0.00021738,
        -0.00016322, -0.00014169]])

In [74]:
pipe = Pipeline([('전처리',MinMaxScaler()), 
                ('알고리즘', RandomForestClassifier(max_depth=16, n_estimators=300))]) 

In [75]:
pipe.fit(x_reduced, y)

Pipeline(steps=[('전처리', MinMaxScaler()),
                ('알고리즘',
                 RandomForestClassifier(max_depth=16, n_estimators=300))])

In [49]:
test = pd.read_csv('../data/test_ver03.csv', index_col='STU_ID')
test = test.drop(columns='F3ONET2CURR')
test.head()

BYSTUWT  BYSEX  BYRACE  BYSTLANG  BYHOMLNG  BYSTLNG2   BYDOB_P  \
STU_ID                                                                    
310221  292.1255    2.0     6.0       1.0       1.0         4  198412.0   
228218  281.6741    1.0     7.0       1.0       1.0         4  198507.0   
179231  275.0641    1.0     7.0       1.0       1.0         4  198607.0   
215101  149.2901    2.0     3.0       1.0       1.0         4  198507.0   
245121  186.5067    1.0     7.0       1.0       1.0         4  198601.0   

        BYFCOMP  BYPARED  BYMOTHED  ...  BYS24C  BYS24D  BYS24E  BYS28  \
STU_ID                              ...                                  
310221      2.0      4.0       4.0  ...     4.0     1.0     1.0    2.0   
228218      6.0      1.0       1.0  ...     3.0     1.0     1.0    2.0   
179231      1.0      4.0       4.0  ...     3.0     1.0     1.0    3.0   
215101      2.0      3.0       1.0  ...     4.0     1.0     3.0    3.0   
245121      5.0      3.0       3.0  ...     2.0     2.0     1.0    2.0   

        BYS71A  BYS71B  BYS71C  BYS71D  BYS71E  BYS71F  
STU_ID                                                  
310221     0.0     1.0     0.0     0.0     1.0     0.0  
228218     0.0     0.0     0.0     0.0     0.0     0.0  
179231     0.0     0.0     0.0     0.0     0.0     0.0  
215101     0.0     0.0     0.0     0.0     0.0     0.0  
245121     0.0     1.0     0.0     0.0     0.0     0.0  

[5 rows x 151 columns]

In [76]:
# test_reduced= pca.fit_transform(test)
test_reduced = rbf_pca.fit_transform(test)

In [77]:
pred = pipe.predict(test_reduced)
pred

array([43, 43, 43, ..., 35, 43, 43], dtype=int64)

In [78]:
submission = pd.DataFrame(pred, index=test.index, columns=['PRED']).reset_index()
submission

STU_ID  PRED
0     310221    43
1     228218    43
2     179231    43
3     215101    43
4     245121    43
...      ...   ...
2474  439214    43
2475  106206    43
2476  272131    35
2477  350228    43
2478  297108    43

[2479 rows x 2 columns]

In [79]:
submission.to_csv('my_pred08.csv', index=False)